//! Scene buffer protocol: decoding the flat typed-array encoding the TS side
//! produces (`encodeScene`) into a `RenderInput`, and encoding render output
//! back into flat buffers. One protocol, two consumers: the wasm boundary
//! (`wasm_api`) and native tooling (`examples/replay.rs` profiling harness).
//!
//! ## Buffer protocol (all little-endian typed arrays from JS)
//!
//! `prims: Float64Array`, stride 9 per primitive:
//!   [kind, ...8 params]
//!   kind 0 line:  p0x p0y p1x p1y  _ _ _ _
//!   kind 1 arc:   cx cy r start sweep  _ _ _
//!   kind 2 cubic: p0x p0y c0x c0y c1x c1y p1x p1y
//!
//! `contours: Uint32Array`, stride 2: [prim_start, prim_count]
//!
//! `shapes_u32: Uint32Array`, stride 12:
//!   [contour_start, contour_count, flags, stroke_pen+1, fill_pen+1,
//!    fill_kind, clip_start, clip_count, fill_start, fill_count,
//!    mod_start, mod_count]
//!   flags: bit0 closed, bit1 convex, bit2 even-odd winding
//!   fill_kind: 0 none, 1 pending (ink arrives at finish as supplied
//!            prims + dots — the two-pass path), 2 mask. The engine
//!            generates no patterns; hatch/stipple are JS fill modules.
//!            Slots 8/9 (old fill_start/fill_count) are reserved-zero.
//!   mod_start/mod_count: this shape's modifier program — mod_count
//!            instructions starting at f64 offset mod_start in `mods`.
//!
//! `shapes_f64: Float64Array`, stride 2: [z, bridge_mm]
//!   bridge_mm: endpoint-join tolerance in paper mm; 0 = shape not opted
//!   into bridging. Opted shapes' strokes are joined pen-down across gaps
//!   up to this size after occlusion (per pen); connector frags carry
//!   flags bit1.
//!
//! `mods: Float64Array` — the modifier tape. Each instruction is
//!   [opcode, field_mask, ...params] with a fixed param count per opcode;
//!   field_mask bit k set means param k is an index into `fields` instead
//!   of a literal. Opcodes (post-stage):
//!     1 decimate: params [stroke_p, fill_p]
//!     2 wobble:   params [amp_mm, wavelength_mm] (wavelength never a field)
//!     3 dash:     params [len_mm, gap_mm, offset_mm]
//!   Opcodes (pre-stage — deform contours before the solve):
//!     4 smooth:   params [passes]
//!     5 roughen:  params [amp_mm, detail_mm]
//!     6 deform:   params [dx_field, dy_field, detail_mm] (dx/dy always
//!                 field refs; mask bits 0 and 1 must be set)
//!
//! `fields: Float64Array` — rasterised scalar fields, concatenated:
//!   each field is [w, h, x0, y0, dx, dy, ...w*h row-major samples] in
//!   paper mm; `Param::Field(i)` refers to the i-th field in order.
//!
//! `clip_list: Uint32Array`: clip region indices, sliced per shape by
//!   clip_start/clip_count.
//!
//! `clips_u32: Uint32Array`, stride 3: [contour_start, contour_count, flags]
//!   clip flags: bit1 convex, bit2 even-odd winding, bit3 INVERT (children
//!   keep the region's OUTSIDE — clip(invert(shape), …))
//!
//! ## Pass-2 supplied ink (`wasm_finish`; the dump-scene sidecar for replay)
//!
//! Fill ink is generated by sketch-space JS between the passes and handed
//! to `finish` as CHAINS — a chain is one connected pen stroke, and the
//! nib rule judges it whole, exactly like an outline contour (a polyline
//! mark is one chain; a lone line/arc/cubic is a chain of one).
//!
//! `fills_index: Uint32Array`, stride 5:
//!   [shape_index, chain_start, chain_count, dot_start(pair), dot_count]
//! `fill_chains: Uint32Array`, stride 2: [prim_start(row), prim_count]
//!   into `fill_prims`
//! `fill_prims: Float64Array`: PRIM stride 9, as above
//! `fill_dots: Float64Array`: xy pairs — intentional taps (strictly-inside
//!   only, occludable, never routed through tap resolution)
//!
//! Output `frags: Float64Array`, stride 6:
//!   [origin_prim, t0, t1, pen, shape, flags(bit0 dot, bit1 bridge)]
//! plus the full primitive table (input prims + generated fill prims) in the
//! same stride-9 encoding, so the preview can draw exact curves.

use crate::bbox::BBox;
use crate::fill::FillKind;
use crate::modifier::{FieldGrid, Modifier, Param};
use crate::pipeline::{ClipDef, Pen, RenderInput, RenderOutput, ShapeRec};
use crate::primitive::{Arc, Cubic, Line, Primitive};
use crate::region::WindingRule;
use crate::vec2::v;

pub const PRIM_STRIDE: usize = 9;
pub const FRAG_STRIDE: usize = 6;
pub const SHAPE_U32_STRIDE: usize = 12;

/// Decode one shape's modifier program from the tape. Fails loudly on an
/// unknown opcode — a positional misread must never render as garbage.
fn decode_modifiers(mods: &[f64], start: usize, count: usize) -> Result<Vec<Modifier>, String> {
    let mut out = Vec::with_capacity(count);
    let mut i = start;
    for _ in 0..count {
        let op = *mods.get(i).ok_or("modifier tape truncated")? as u32;
        let mask = *mods.get(i + 1).ok_or("modifier tape truncated")? as u32;
        let nparams = match op {
            1 | 2 | 5 => 2,
            4 => 1,
            3 | 6 => 3,
            _ => return Err(format!("unknown modifier opcode {op}")),
        };
        let param = |k: usize| -> Result<Param, String> {
            let raw = *mods.get(i + 2 + k).ok_or("modifier tape truncated")?;
            Ok(if mask & (1 << k) != 0 {
                Param::Field(raw as u32)
            } else {
                Param::Lit(raw)
            })
        };
        let lit = |k: usize, what: &str| -> Result<f64, String> {
            param(k)?
                .literal()
                .ok_or(format!("{what} cannot be a field"))
        };
        out.push(match op {
            1 => Modifier::Decimate {
                stroke: param(0)?,
                fill: param(1)?,
            },
            2 => Modifier::Wobble {
                amp: param(0)?,
                wavelength: lit(1, "wobble wavelength")?,
            },
            3 => Modifier::Dash {
                len: lit(0, "dash length")?,
                gap: lit(1, "dash gap")?,
                offset: lit(2, "dash offset")?,
            },
            4 => Modifier::Smooth {
                passes: (lit(0, "smooth passes")? as u32).min(8),
            },
            5 => Modifier::Roughen {
                amp: param(0)?,
                detail: lit(1, "roughen detail")?,
            },
            _ => Modifier::Deform {
                dx: param(0)?,
                dy: param(1)?,
                detail: lit(2, "deform detail")?,
            },
        });
        i += 2 + nparams;
    }
    Ok(out)
}

/// Decode the concatenated field rasters buffer.
fn decode_fields(fields: &[f64]) -> Result<Vec<FieldGrid>, String> {
    let mut out = Vec::new();
    let mut i = 0;
    while i < fields.len() {
        if i + 6 > fields.len() {
            return Err("field buffer truncated".into());
        }
        let (w, h) = (fields[i] as usize, fields[i + 1] as usize);
        let n = w * h;
        if i + 6 + n > fields.len() {
            return Err("field samples truncated".into());
        }
        out.push(FieldGrid {
            w,
            h,
            x0: fields[i + 2],
            y0: fields[i + 3],
            dx: fields[i + 4],
            dy: fields[i + 5],
            samples: fields[i + 6..i + 6 + n].to_vec(),
        });
        i += 6 + n;
    }
    Ok(out)
}

fn decode_prim(row: &[f64]) -> Primitive {
    match row[0] as u32 {
        0 => Primitive::Line(Line::new(v(row[1], row[2]), v(row[3], row[4]))),
        1 => Primitive::Arc(Arc::new(v(row[1], row[2]), row[3], row[4], row[5])),
        _ => Primitive::Cubic(Cubic::new(
            v(row[1], row[2]),
            v(row[3], row[4]),
            v(row[5], row[6]),
            v(row[7], row[8]),
        )),
    }
}

pub fn encode_prim(p: &Primitive, out: &mut Vec<f64>) {
    match p {
        Primitive::Line(l) => {
            out.extend_from_slice(&[0.0, l.p0.x, l.p0.y, l.p1.x, l.p1.y, 0.0, 0.0, 0.0, 0.0])
        }
        Primitive::Arc(a) => out.extend_from_slice(&[
            1.0, a.center.x, a.center.y, a.r, a.start, a.sweep, 0.0, 0.0, 0.0,
        ]),
        Primitive::Cubic(c) => out.extend_from_slice(&[
            2.0, c.p0.x, c.p0.y, c.c0.x, c.c0.y, c.c1.x, c.c1.y, c.p1.x, c.p1.y,
        ]),
    }
}

pub fn decode_prims(prims: &[f64]) -> Vec<Primitive> {
    prims.chunks_exact(PRIM_STRIDE).map(decode_prim).collect()
}

fn contours_of(
    contour_start: usize,
    contour_count: usize,
    contours: &[u32],
    table: &[Primitive],
) -> Result<Vec<Vec<Primitive>>, String> {
    let end = contour_start
        .checked_add(contour_count)
        .filter(|&e| e * 2 <= contours.len())
        .ok_or("contour range out of bounds")?;
    (contour_start..end)
        .map(|ci| {
            let ps = contours[ci * 2] as usize;
            let pc = contours[ci * 2 + 1] as usize;
            let pe = ps
                .checked_add(pc)
                .filter(|&e| e <= table.len())
                .ok_or("contour primitive range out of bounds")?;
            Ok(table[ps..pe].to_vec())
        })
        .collect()
}

/// Decode the whole scene buffer set into a `RenderInput` — validation and
/// all. The one place the buffer protocol is interpreted.
#[allow(clippy::too_many_arguments)]
pub fn decode_render_input(
    prims: &[f64],
    contours: &[u32],
    shapes_u32: &[u32],
    shapes_f64: &[f64],
    mods: &[f64],
    field_data: &[f64],
    clip_list: &[u32],
    clips_u32: &[u32],
    pens_json: &str,
    paper: &[f64],
    seed: u32,
    coarsen: f64,
    debug_ghost: u32,
) -> Result<RenderInput, String> {
    let err = |m: &str| m.to_string();
    if prims.len() % PRIM_STRIDE != 0 {
        return Err(err("prims buffer not a multiple of the stride"));
    }
    if shapes_u32.len() % SHAPE_U32_STRIDE != 0 {
        return Err(err("shapes_u32 buffer not a multiple of the stride"));
    }
    if clips_u32.len() % 3 != 0 || contours.len() % 2 != 0 {
        return Err(err("clip/contour buffer not a multiple of the stride"));
    }
    if prims.iter().any(|v| !v.is_finite()) {
        return Err(err("non-finite value in prims buffer"));
    }
    if paper.iter().any(|v| !v.is_finite()) {
        return Err(err("non-finite paper bounds"));
    }
    let table = decode_prims(prims);
    let pens: Vec<Pen> =
        serde_json::from_str(pens_json).map_err(|e| format!("bad pens json: {e}"))?;
    let fields = decode_fields(field_data)?;

    let n = shapes_u32.len() / SHAPE_U32_STRIDE;
    if shapes_f64.len() < n * 2 {
        return Err(err("shapes_f64 shorter than shape count"));
    }
    let mut shapes = Vec::with_capacity(n);
    for i in 0..n {
        let s = &shapes_u32[i * SHAPE_U32_STRIDE..(i + 1) * SHAPE_U32_STRIDE];
        let flags = s[2];
        let closed = flags & 1 != 0;
        let winding = if flags & 4 != 0 {
            WindingRule::EvenOdd
        } else {
            WindingRule::NonZero
        };
        if s[4] == 0 && (1..=2).contains(&s[5]) {
            return Err(err("fill kind set without a fill pen"));
        }
        let fill = match s[5] {
            1 => Some((s[4] - 1, FillKind::Pending)),
            2 => Some((s[4] - 1, FillKind::Mask)),
            _ => None,
        };
        let clip_end = (s[6] as usize)
            .checked_add(s[7] as usize)
            .filter(|&e| e <= clip_list.len())
            .ok_or(err("clip list range out of bounds"))?;
        shapes.push(ShapeRec {
            contours: contours_of(s[0] as usize, s[1] as usize, contours, &table)?,
            closed,
            convex: flags & 2 != 0,
            winding,
            stroke: if s[3] > 0 { Some(s[3] - 1) } else { None },
            fill,
            z: shapes_f64[i * 2],
            bridge_mm: shapes_f64[i * 2 + 1],
            clips: clip_list[s[6] as usize..clip_end].to_vec(),
            modifiers: decode_modifiers(mods, s[10] as usize, s[11] as usize)?,
        });
    }

    let clips: Vec<ClipDef> = clips_u32
        .chunks_exact(3)
        .map(|c| {
            Ok(ClipDef {
                contours: contours_of(c[0] as usize, c[1] as usize, contours, &table)?,
                winding: if c[2] & 4 != 0 {
                    WindingRule::EvenOdd
                } else {
                    WindingRule::NonZero
                },
                convex: c[2] & 2 != 0,
                invert: c[2] & 8 != 0,
            })
        })
        .collect::<Result<_, String>>()?;

    let paper_box = if paper.len() == 4 {
        Some(BBox::new(v(paper[0], paper[1]), v(paper[2], paper[3])))
    } else {
        None
    };

    Ok(RenderInput {
        shapes,
        clips,
        pens,
        paper: paper_box,
        seed: seed as u64,
        coarsen,
        fields,
        debug_ghost: debug_ghost != 0,
    })
}

/// Flat-buffer render output: exactly what crosses the wasm boundary.
pub struct EncodedOutput {
    pub prims: Vec<f64>,
    pub frags: Vec<f64>,
    pub stats: Vec<f64>,
    pub ghost: Vec<f64>,
}

/// Encode render output into the flat buffers the preview consumes.
pub fn encode_render_output(out: &RenderOutput) -> EncodedOutput {
    let mut prims_out = Vec::with_capacity(out.prims.len() * PRIM_STRIDE);
    for p in &out.prims {
        encode_prim(p, &mut prims_out);
    }
    let mut frags_out = Vec::with_capacity(out.frags.len() * FRAG_STRIDE);
    for f in &out.frags {
        frags_out.extend_from_slice(&[
            f.origin as f64,
            f.t0,
            f.t1,
            f.pen as f64,
            f.shape as f64,
            (if f.dot { 1.0 } else { 0.0 }) + (if f.bridge { 2.0 } else { 0.0 }),
        ]);
    }
    let mut ghost_out = Vec::with_capacity(out.ghost.len() * PRIM_STRIDE);
    for p in &out.ghost {
        encode_prim(p, &mut ghost_out);
    }
    let s = &out.stats;
    EncodedOutput {
        prims: prims_out,
        frags: frags_out,
        ghost: ghost_out,
        stats: vec![
            s.shapes_in as f64,
            s.culled_off_paper as f64,
            s.culled_contained as f64,
            s.clean as f64,
            s.fragments as f64,
            s.fill_prims as f64,
        ],
    }
}
