/** Served Studio check of the camera view: switch placement, no layout shift, Blender keys, commit into the view call. */
import {chromium} from 'playwright';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import assert from 'node:assert/strict';
const base=process.env.OCCLUDE_GPU_URL??'http://127.0.0.1:5273',out=process.env.OCCLUDE_API_EVIDENCE??'../../development/3d/camera-controls/live',stamp=process.env.OCCLUDE_STAMP??'bae1191-camera-controls';
const sources=[...(await readFile('../../docs/three.md','utf8')).matchAll(/```ts live[^\n]*\n([\s\S]*?)```/g)].map(m=>m[1]);
const example=Number(process.env.OCCLUDE_EXAMPLE??'26');
await mkdir(out,{recursive:true});
const browser=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:false,env:{...process.env,VK_DRIVER_FILES:'/usr/share/vulkan/icd.d/nvidia_icd.json'},args:['--no-sandbox','--enable-unsafe-webgpu','--enable-features=Vulkan','--use-angle=vulkan','--disable-vulkan-surface','--ignore-gpu-blocklist']});
const errors=[];
try{
 const page=await browser.newPage({viewport:{width:1400,height:900}});page.on('pageerror',e=>errors.push(String(e)));
 await page.addInitScript(source=>{localStorage.setItem('occlude.sketch',source);const Original=Worker;window.Worker=class extends Original{constructor(...a){super(...a);this.addEventListener('message',e=>{if(e.data.type==='render'){window.reply=e.data;window.count=(window.count??0)+1;}});}};},sources[example]);
 await page.goto(base);await page.waitForFunction(s=>document.querySelector('#status-build')?.textContent.includes(s),stamp);
 await page.waitForFunction(()=>window.reply&&document.querySelector('#status-msg').textContent==='ok',{},{timeout:90000});
 const rect=async sel=>page.evaluate(s=>{const r=document.querySelector(s).getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};},sel);
 const sw=await rect('.view-switch'),bench=await rect('#bench'),paper=await rect('#preview');
 assert(sw.x+sw.w>bench.x+bench.w-40&&sw.y+sw.h>bench.y+bench.h-40,'switch sits bottom right of the sketch');
 await page.click('.view-switch button[aria-label="3D camera view"]');
 await page.waitForFunction(()=>!document.querySelector('#construction-canvas').hidden&&document.querySelector('#construction-canvas').width>0);
 await page.waitForTimeout(800);
 const overlay=await rect('#construction-canvas');
 assert.deepEqual(overlay,paper,'construction canvas covers exactly the sketch canvas');
 assert.deepEqual(await rect('#preview'),paper,'switching moved nothing');
 await page.screenshot({path:out+'/camera-view.png'});
 const before=await page.evaluate(()=>document.querySelector('#construction-canvas').toDataURL().length);
 await page.focus('#construction-canvas');await page.keyboard.press('Numpad7');await page.waitForTimeout(600);
 await page.screenshot({path:out+'/top-view.png'});
 const after=await page.evaluate(()=>document.querySelector('#construction-canvas').toDataURL().length);
 assert(before!==after,'numpad 7 changed the view');
 await page.keyboard.press('Home');await page.waitForTimeout(400);
 const box=await page.locator('#construction-canvas').boundingBox();
 await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+120,box.y+box.height/2+40,{steps:8});await page.mouse.up();await page.waitForTimeout(600);
 const prior=await page.evaluate(()=>window.count),sourceBefore=await page.evaluate(()=>window.__occlude.editor.getValue());
 await page.click('.construction-toolbar button:has-text("Commit view")');
 await page.waitForFunction(n=>window.count>n&&document.querySelector('#status-msg').textContent==='ok',prior,{timeout:90000});
 await page.waitForTimeout(500);
 const sourceAfter=await page.evaluate(()=>window.__occlude.editor.getValue());
 assert.notEqual(sourceAfter,sourceBefore,'commit edited the source');
 assert(!sourceAfter.includes('cameras3'),'camera written into the view call, not a cameras3 map');
 assert(/camera: (orthographic|perspective)\(\{ eye: \[/.test(sourceAfter),'view call carries the committed camera');
 await page.click('.view-switch button[aria-label="Sketch view"]');await page.waitForTimeout(300);
 assert.deepEqual(await rect('#preview'),paper,'returning to the sketch moved nothing');
 await page.screenshot({path:out+'/committed.png'});
 await writeFile(out+'/committed-source.ts',sourceAfter);
 assert.deepEqual(errors,[]);
 await writeFile(out+'/report.json',JSON.stringify({passed:true,base,stamp,example:`three#${example}`,switch:sw,paper,overlay},null,2)+'\n');console.log(JSON.stringify({passed:true}));
}catch(e){await writeFile(out+'/failure.json',JSON.stringify({errors,error:String(e)},null,2));throw e;}finally{await browser.close();}
